"""empty message

Revision ID: 2762de744697
Revises: a321b292f29f
Create Date: 2018-05-17 13:54:32.125283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2762de744697'
down_revision = 'a321b292f29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_catalog', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=3072),
               existing_nullable=False)
    op.alter_column('movie_catalog', 'revenue',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=8, asdecimal=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_catalog', 'revenue',
               existing_type=sa.Numeric(precision=8, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('movie_catalog', 'description',
               existing_type=sa.String(length=3072),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
