"""empty message

Revision ID: 319a222dc2af
Revises: 
Create Date: 2018-05-01 09:54:04.570007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319a222dc2af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user', type_='unique')
    # ### end Alembic commands ###
